---
openapi: 3.0.1
info:
  title: API V1
  version: v1
  description: |2

    ### Instrucciones para autenticación JWT

    1. Regístrate o haz login usando los endpoints `/api/v1/register` o `/api/v1/login`.
    2. Copia el token JWT que devuelve la respuesta.
    3. Haz clic en el botón 'Authorize' (arriba a la derecha en Swagger UI).
    4. Pega el token en el campo 'Bearer' y confirma.
    5. Ahora puedes hacer peticiones a los endpoints protegidos.

    El token se debe pegar con el prefijo `Bearer ` (Swagger lo agrega automáticamente).
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  "/api/v1/register":
    post:
      summary: Register a new user
      tags:
      - Auth
      parameters: []
      responses:
        '201':
          description: user created
        '422':
          description: email already taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: John Doe
                email:
                  type: string
                  example: john.doe@example.com
                password:
                  type: string
                  example: password123
                password_confirmation:
                  type: string
                  example: password123
              required:
              - name
              - email
              - password
              - password_confirmation
  "/api/v1/login":
    post:
      summary: Login a user
      tags:
      - Auth
      parameters: []
      responses:
        '200':
          description: login successful
        '401':
          description: login with non-existent email
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: john.doe@example.com
                password:
                  type: string
                  example: password123
              required:
              - email
              - password
  "/api/v1/currencies/btc_price":
    get:
      summary: Gets the price of BTC
      tags:
      - Currencies
      responses:
        '200':
          description: price fetched
        '502':
          description: coingecko error
  "/api/v1/users/{user_id}/transactions":
    parameters:
    - name: user_id
      in: path
      required: true
      schema:
        type: integer
    post:
      summary: Creates a transaction
      security:
      - Bearer: []
      tags:
      - Transactions
      parameters: []
      responses:
        '201':
          description: transaction created
        '422':
          description: invalid request
        '401':
          description: unauthorized when no token
        '403':
          description: forbidden for other user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                from_currency:
                  type: string
                  enum:
                  - usd
                  - bitcoin
                to_currency:
                  type: string
                  enum:
                  - bitcoin
                  - usd
                amount_from:
                  type: number
                  format: float
                  default: 50.0
              required:
              - from_currency
              - to_currency
              - amount_from
    get:
      summary: Gets all transactions
      security:
      - Bearer: []
      tags:
      - Transactions
      responses:
        '200':
          description: transactions found
  "/api/v1/users/{user_id}/transactions/{id}":
    parameters:
    - name: user_id
      in: path
      required: true
      schema:
        type: integer
    - name: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Gets a transaction
      security:
      - Bearer: []
      tags:
      - Transactions
      responses:
        '200':
          description: transaction found
        '404':
          description: transaction not found for wrong user
